const mongoose = require("mongoose");
const roomSchema = new mongoose.Schema(
  {
    roomname: {
      $type: String,
      required: true,
    },
    singleroom: { $type: Boolean },
    users: [
      {
        username: String,
        lineColor: String,
        lineWidth: Number,
        fillColor: String,
        opacity: Number,
        strokeDashArray: Number,
        shape: String,
        lock: Boolean,
        showSidebar: Boolean,
      },
    ],
    figures: [
      {
        type: String,
        version: String,
        strokeDashArray: Array,
        strokeLineCap: String,
        strokeDashOffset: Number,
        strokeLineJoin: String,
        strokeUniform: Boolean,
        strokeMiterLimit: Number,
        scaleX: Number,
        scaleY: Number,
        flipX: Boolean,
        flipY: Boolean,
        opacity: Number,
        shadow: String,
        visible: Boolean,
        backgroundColor: String,
        fillRule: String,
        paintFirst: String,
        globalCompositeOperation: String,
        skewX: Number,
        skewY: Number,
        id: String,
        left: Number,
        top: Number,
        rx: Number,
        ry: Number,
        originX: String,
        originY: String,
        angle: Number,
        fill: String,
        stroke: String,
        strokeWidth: Number,
        width: Number,
        height: Number,
        x1: Number,
        x2: Number,
        y1: Number,
        y2: Number,
        path: Array,
        clipPath: Object,
      },
    ],
  },
  { typeKey: "$type" }
);

const Room = mongoose.model("Room", roomSchema);
module.exports = Room;
